{
    [
        './maker/*',
        '../../src/tool/*/*',
        '../../src/lib/mysql/*'
    ],
    [
        {i, "../../include"},
        {outdir, "../../beam/"},
        warnings_as_errors,
        native,
        {hipe, o3}
    ]
}.
