{
    [
        './maker/*',
        '../../src/tool/*',
        '../../src/tool/*/*'
    ],
    [
        {i, "../../include"},
        {outdir, "../../beam/"},
        warnings_as_errors,
        native,
        {hipe, o3}
    ]
}.
