{
    [
        '../../src/*',
        '../../src/*/*',
        '../../src/*/*/*',
        '../../src/*/*/*/*'
    ],
    [
        {i, "../../include/"},
        {outdir, "../../beam/"},
        debug_info,
        {d, 'DEBUG'}
    ]
}.
