{
    [
        '../../src/*',
        '../../src/*/*',
        '../../src/*/*/*',
        '../../src/*/*/*/*'
    ],
    [
        {i, "../../include/"},
        {outdir, "../../beam/"},
        {d, 'DEBUG'},
        {d, pre17}  %% otp 17 or earlier, referring to built-in type queue as a remote type; please take out the module name
    ]
}.
